version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the GPU Docker image...
      - echo Building the CPU Docker image...
      - docker build -t $IMAGE_REPO_NAME:cpu fastai-cpu
      - docker tag $IMAGE_REPO_NAME:cpu $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:cpu
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the CPU Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:cpu
